import React from 'react';
import {MyStylesheet} from './styles'

class Privacy {

    showprivacy() {
        const styles = MyStylesheet();
        return(
            <div>
                <div style={{...styles.font24, ...styles.regularFont}}>Privacy Policy</div>
                <div style={{...styles.font20, ...styles.regularFont}}>Our Privacy Policy was posted on 6 November 2019 and last updated on 22 Mar 2020. It governs the privacy terms of our website, located at civilengineer.io, and the tools we provide you (the "Website" or the "Service"). Any capitalized terms not defined in our Privacy Policy, have the meaning as specified in our Terms of Use accessible at https://civilengineer.io </div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Your Privacy</div>
                <div style={{...styles.font20, ...styles.regularFont}}>Our Website follows all legal requirements to protect your privacy. Our Privacy Policy is a legal statement that explains how we may collect information from you, how we may share your information, and how you can limit our sharing of your information. You will see terms in our Privacy Policy that are capitalized. These terms have meanings as described in the Definitions section below.</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Definitions</div>
                <div style={{...styles.font20, ...styles.regularFont}}>
                    <ul>
                        <li>Personal Data: Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                        <li>Usage Data: Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                        <li>Cookies: Cookies are small pieces of data stored on a User's device.</li>
                        <li>Data Controller: Data Controller means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
                        <li>Data Processors (or Service Providers): Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
                        <li>Data Subject: Data Subject is any living individual who is the subject of Personal Data.</li>
                        <li>User: The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
                    </ul>
                </div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Information Collection And Use</div>
                <div style={{...styles.font20, ...styles.regularFont}}>We collect several different types of information for various purposes to provide and improve our Service to you.</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Types of Data Collected</div>
                <div style={{...styles.font20, ...styles.regularFont}}>Personal Data</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to: Email address, Name, Address, State, Province, ZIP/Postal code, City, Cookies and Usage Data.</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Usage Data</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Tracking & Cookies Data </div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>Examples of Cookies we use: session cookies (we use these cookies to operate our Service) and preference cookies (we use these cookies to remember your preferences and various settings).</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Use of Data</div>
                <div style={{...styles.font20, ...styles.regularFont}}>We use the collected data for various purposes:
            <ul>
                        <li>To provide and maintain our Service</li>
                        <li>To notify you about changes to our Service</li>
                        <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                        <li>To provide customer support</li>
                        <li>To gather analysis or valuable information so that we can improve our Service</li>
                        <li>To monitor the usage of our Service</li>
                        <li>To detect, prevent and address technical issues</li>
                        <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                    </ul>
                </div>
                <div style={{...styles.font24, ...styles.regularFont}}>Retention of Data</div>
                <div style={{...styles.font20, ...styles.regularFont}}>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Transfer Of Data</div>
                <div style={{...styles.font20, ...styles.regularFont}}>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</div>
        
        
                <div style={{...styles.font20, ...styles.regularFont}}>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Disclosure Of Data</div>
                <div style={{...styles.font20, ...styles.regularFont}}>Business Transaction. If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
        Disclosure for Law Enforcement. Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</div>
                <div style={{...styles.font24, ...styles.regularFont}}>Security Of Data</div>
                <div style={{...styles.font20, ...styles.regularFont}}>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</div>
                <div style={{...styles.font20, ...styles.regularFont}}>If you are from the European Economic Area (EEA), Civilengineer.io legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it. </div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>CivilEngineer may process your Personal Data because:
                    <ul>
                        <li>We need to perform a contract with you</li>
                        <li>You have given us permission to do so</li>
                        <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
                        <li>For payment processing purposes</li>
                        <li>To comply with the law</li>
                    </ul>
        
                </div>
        
                <div style={{...styles.font24, ...styles.regularFont}}>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Civilengineer.io aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. </div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us. </div>
        
                <div style={{...styles.font20, ...styles.regularFont}}>In certain circumstances, you have the following data protection rights:
        
                        <ul>
                            <li>The right to access, update or to delete the information we have on you.</li>
        
                            <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
        
                            <li>The right to object. You have the right to object to our processing of your Personal Data.</li>
        
                            <li>The right of restriction. You have the right to request that we restrict the processing of your personal information.</li>
        
                            <li>The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format.</li>
        
                            <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where Civilengineer.io relied on your consent to process your personal information.</li>
        
                            <li>Please note that we may ask you to verify your identity before responding to such requests.</li>
        
                            <li>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</li>
                        </ul>
                    </div>
                    <div style={{...styles.font24, ...styles.regularFont}}>Do Not Sell My Personal Information" Notice for California consumers under California Consumer Privacy Act (CCPA) </div>
                    <div style={{...styles.font20, ...styles.regularFont}}>Under the CCPA, California consumers have the right to:
        <ul>
        <li>Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</li>
        <li>Request that a business delete any personal data about the consumer that a business has collected.</li>
        <li>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
        </ul>
        If you make a request, we have 30 days to respond to you. If you would like to exercise any of these rights, please contact us.
        </div>
        <div style={{...styles.font24, ...styles.regularFont}}>Service Providers</div>
        <div style={{...styles.font20, ...styles.regularFont}}>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</div>
        
        <div style={{...styles.font24, ...styles.regularFont}}>Analytics</div>
        <div style={{...styles.font20, ...styles.regularFont}}>We may use third-party Service Providers to monitor and analyze the use of our Service.</div>
        
        <div style={{...styles.font24, ...styles.regularFont}}>Google Analytics</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: http://www.google.com/intl/en/policies/privacy/</div>
        
        <div style={{...styles.font24, ...styles.regularFont}}>Payments</div>
        <div style={{...styles.font20, ...styles.regularFont}}>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</div>
        <div style={{...styles.font20, ...styles.regularFont}}>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>The payment processors we work with are:</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>Stripe. Their Privacy Policy can be viewed at https://stripe.com/privacy</div>
        
        <div style={{...styles.font24, ...styles.regularFont}}>Links To Other Sites</div>
        <div style={{...styles.font20, ...styles.regularFont}}>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</div>
        <div style={{...styles.font20, ...styles.regularFont}}>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</div>
        
        <div style={{...styles.font24, ...styles.regularFont}}>Children's Privacy</div>
        <div style={{...styles.font20, ...styles.regularFont}}>Our Service does not address anyone under the age of 18 ("Children").</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</div>
        
        <div style={{...styles.font24, ...styles.regularFont}}>Changes To This Privacy Policy</div>
        <div style={{...styles.font20, ...styles.regularFont}}>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</div>
        
        <div style={{...styles.font20, ...styles.regularFont}}>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</div>
        
        <div style={{...styles.font24, ...styles.regularFont}}>Contact Us</div>
        <div style={{...styles.font20, ...styles.regularFont}}>If you have any questions about this Privacy Policy, please contact us by using the contact information we provided on our Contact page.</div>
        </div>
        )
        
        }
}
export default Privacy;